### ISSUE TITLE
Latest update (0.4.92) with error; integration doesn't work anymore

### ISSUE THREAD

**Issue by cbornBerlin** [tschamm/boschshc-hass#201]
Just updated to the newest version and discovered a bug as it seems. Had to revert back to the prior version which fixed the problem.
After updating and restarting, the integration doesn't work anymore.

Here is some error log for what it's worth.

Protokolldetails (FEHLER)
Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 17:31:31 (1 Vorkommnisse)
Zuletzt protokolliert: 17:31:31

Error setting up entry shc11019a for bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_shc/__init__.py", line 135, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2147, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 8 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bosch_shc/alarm_control_panel.py", line 4, in <module>
    from homeassistant.components.alarm_control_panel.const import (
ImportError: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel.const' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/const.py)

**Comment by brian0400** [comment]
same problems

**Comment by Nr5-Mike** [comment]
same here...

**Comment by Hellfirefox** [comment]
Same problem for me.

**Comment by tschamm** [comment]
As written in the release notes, the current release works with HA>=2024.11.0. So please update HA before updating the integration

**Comment by cbornBerlin** [comment]
I somehow missed this. Thanks. I read about the change itself but not about the version requirement. Just updated HA, updated SHC. All good.

**Comment by Nr5-Mike** [comment]
Works fine now. Note to myself: RTFM!
