### ISSUE TITLE
Switches are not running after update to 0.4.94

### ISSUE THREAD

**Issue by GefallenFallen** [tschamm/boschshc-hass#221]
Hi,
after updating to version 0.4.94, the user defined switches are not running anymore.
With version 0.4.93 everything is running fine.

Was there any change in this direction?

Thanks

**Comment by Matze89x** [comment]
I can confirm that. The buttons no longer work for the self-created scenarios -> states. 

![image](https://github.com/user-attachments/assets/dc4106e7-fa2c-4933-8b58-650fe1a74f6c)


Error while setting up bosch_shc platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/bosch_shc/switch.py", line 403, in async_setup_entry
    async_add_userdefinedstateswitch(switch=switch)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch_shc/switch.py", line 392, in async_add_userdefinedstateswitch
    switch = SHCUserDefinedStateSwitch(
        device=switch,
    ...<3 lines>...
        description=SWITCH_TYPES["user_defined_state"],
    )
  File "/config/custom_components/bosch_shc/switch.py", line 489, in __init__
    f"{device.root_device_id}_{device.id}"
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SHCUserDefinedState' object has no attribute 'root_device_id'
