### ISSUE TITLE
Bosch Water 

### ISSUE THREAD

**Issue by christianreiss** [tschamm/boschshc-hass#27]
Hey,

the Water Alarm (https://www.bosch-smarthome.com/uk/en/products/devices/water-alarm/) does not show up. Seems to be trivial to include? Should work like the smoke detectors which should work the same.

I can supply you with any data you might require.

Thanks!

**Comment by tschamm** [comment]
If possible you can provide the services of the water alarm, as well as the service states.

Of course you can also implement it by yourself, I will be happy to review and give feedback!

**Comment by tschamm** [comment]
@christianreiss The water leakage sensor was already added in the `boschshcpy` library. I added the basic functionality for a binary sensor and published a pre-release version: https://github.com/tschamm/boschshc-hass/tree/0.4.2.dev0

Can you please test if the sensor is detected, and if state change is reported correctly?

**Comment by christianreiss** [comment]
I am sorry I only got time for this now.
Life was hell (was moving in real live). Internet etc back up.

Is the proposed change still only in 0.4.2-dev0 or was it merged/  moved already?

**Comment by tschamm** [comment]
Congratulations then to your new living place!
The enhancement is already added in 0.4.2. Nevertheless, I would be very happy if you can confirm the water leak sensor woring properly.

**Comment by christianreiss** [comment]
Thanks :)

I checked out currrent master release, restarted HA and even the integration (which is pointless) but still no water detection device. It is visible in the Bosch App, but not in HA. I checked all detected entries manually.

**Comment by tschamm** [comment]
Thanks for reporting! Maybe the device implementation on boschshcpy side is not fully working. Can you provide the following info, e.g. via `postman`:

* `deviceModel` of the water detection sensor
* `deviceServiceIds` of the water detection sensor
 
That would be great!

**Comment by christianreiss** [comment]
Humm,

could you give me quick commands to give you the data? Thanks :)

**Comment by steffann1968** [comment]
Hey,
due to I have the same issue, here my log from postman: 
  
        "deviceServiceIds": [
            "CommunicationQuality",
            "BatteryLevel",
            "WaterLeakageSensorTilt",
            "WaterLeakageSensor",
            "WaterLeakageSensorCheck"
        ],
        "manufacturer": "BOSCH",
        "deviceModel": "WLS",
  
  By the way, thanks for your work & time doing this great project.

**Comment by tschamm** [comment]
Thanks for the log, the deviceModel was actually different to what I expected. I fixed this in [boschshcpy==0.2.18](https://github.com/tschamm/boschshcpy/releases/tag/0.2.18), which is pulled by https://github.com/tschamm/boschshc-hass/commit/46949e533908f08333c477f876cc34a1e858a7c9
Can you give feedback, if it works now?

**Comment by steffann1968** [comment]
After updating to 0.43 I get following error message:

_Error while setting up bosch_shc platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bosch_shc/binary_sensor.py", line 94, in async_setup_entry
    WaterLeakageDetectorSensor(
TypeError: __init__() got an unexpected keyword argument 'hass'_

If you need more information, please let me know.

**Comment by tschamm** [comment]
Thanks for reporting! I provided a hotfix for 0.4.3, can you test it?

**Comment by steffann1968** [comment]
Perfect, thanks.
It's in now.
![image](https://user-images.githubusercontent.com/73201240/119409235-48d02580-bce7-11eb-9b22-28b67e7f391b.png)

Should the tilt message also be available as binary?

**Comment by tschamm** [comment]
Tilt message will be available via attributes of the entity.

**Comment by steffann1968** [comment]
Sorry, I am not so confirm with the attributes. But should it been visible in the entity card configuration like the twinguard?
Or do I have to configure this inside the sensors.yaml?
![image](https://user-images.githubusercontent.com/73201240/119655667-23980000-be2a-11eb-91be-8a9c39752d2c.png)

**Comment by steffann1968** [comment]
I was still on version 0.4.4 and after update to 0.4.5 I could see the state of push_notification and acoustic_signal.
Sorry for confusion. Tilt state I could still not see.
![image](https://user-images.githubusercontent.com/73201240/119716183-23692600-be65-11eb-80b4-81ef6e32b2b6.png)
![image](https://user-images.githubusercontent.com/73201240/119716192-26fcad00-be65-11eb-96de-5893d4659007.png)

**Comment by tschamm** [comment]
Good to hear you can see the `push_notification` and `acoustic_signal` states. What are you missing from the tilt state. AFAIK, the `WaterLeakageSensorTilt` service reports only those two states.

**Comment by steffann1968** [comment]
When the sensor is moved e.g. by hand I get a warning message in the Bosch Smart Up "Der Wassermelder wurde bewegt"
When I disable the "Push notification message" I don't get this message.
Refer to attached picture.
I don't know how to get the "Tilt message"  in home assistant.
Same for battery status.
![image](https://user-images.githubusercontent.com/73201240/121051623-e0d71000-c7b9-11eb-8963-1a293b7f1d4c.png)
